# -*- coding: utf-8 -*-
"""Untitled_mym_week1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BgcK5GYTIM48qDu_7J3KuXRT6IWmky7a
"""

from google.colab import files #The data is collected from job listing websites in the United States. The data is related to different states in the United States. It is collected using web scraping and stored in a CSV file. We will work on the data as data scientists.
uploaded = files.upload()

import pandas as pd #We are using the Pandas library.(1.Pandas can be used to read data from a CSV file and store it in a DataFrame.2.Pandas can be used to calculate the mean, median, and standard deviation of a DataFrame.3.andas can be used to plot data from a DataFrame.)
df = pd.read_csv('df.csv')
df

df.head() #Print the first five rows, including row 0

df.tail() #Print the last five rows

df.info() #1The df.info() method in the Pandas library displays general information about a DataFrame. This information includes:1.The number of rows and columns2.The column names3.The data type of each column4.The number of non-null values in each column5.The nmber of null values in each column6.The amount of memory used by the DataFrame